import Head from 'next/head'
import { useState } from 'react';
import CoinList from '../features/CoinList';

export default function Home(props) {
  const [search, setSearch] = useState('');

  const allCoins = props.filteredCoins;

  const handleChange = e => {
    e.preventDefault();
    console.log(props.filteredCoins);
    setSearch(e.target.value.toLowerCase());
  };

  return (
    <div>
      <Head>
        <title>Crypto currency app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <CoinList filteredCoins={allCoins}/>        
    </div>
  )
}


export const getServerSideProps = async () => {
  const x = async function  () {
    const res = await fetch('https://api.coindesk.com/v1/bpi/currentprice.json')
    const filteredCoins = await res.json();  
    return filteredCoins;
  }
  setInterval( x, 1000);
  const filteredCoin = x();
  return{
    props: {
      filteredCoin
    }
  }
}
